<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="Home-PC" tests="2" failures="1" timestamp="11 May 2015 17:41:02 GMT" time="0.025" errors="0">
  <testcase name="seventeenShouldBePrimeTest" time="0.01" classname="PrimerNumberCheckerTest"/>
  <testcase name="seventeenShouldBePrimeTest1" time="0.0" classname="PrimerNumberCheckerTest">
    <failure type="java.lang.AssertionError" message="Number 17 is said to be not prime, but we were expected prime number expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: Number 17 is said to be not prime, but we were expected prime number expected:<true> but was:<false>
	at PrimerNumberCheckerTest.seventeenShouldBePrimeTest1(PrimerNumberCheckerTest.java:24)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 29 stack frames]]>
    </failure>
  </testcase>
</testsuite>
